apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-service-monitor
  namespace: eks-app
  labels:
    app: mysql
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - eks-app
  selector:
    matchLabels:
      app: mysql