apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-service-monitor
  namespace: monitoring
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  namespaceSelector:
    any: true
  endpoints:
    - port: db-port
      path: /metrics
      interval: 20s