apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-service-monitor
  namespace: eks-app
  labels:
    app.kubernetes.io/name: test-app
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - eks-app
  selector:
    matchLabels:
      app.kubernetes.io/name: test-app