apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
      app.kubernetes.io/instance: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
        app.kubernetes.io/instance: eks-app
    spec:
      containers:
        - name: eks-app
          image: 710271920179.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:912babad24db1b391852232ec8508a60c01ab01b
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          env:
#            - name: SPRING_DATASOURCE_URL
#              value: "jdbc:mysql://mysql-service:3306/app?serverTimezone=Asia/Seoul"
#            - name: SPRING_DATASOURCE_USERNAME
#              value: "app"
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: "app12345"