apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: test-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-app
    spec:
      containers:
        - name: test-app
          image: 710271920179.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:d3d25247c03d18baf9d42a2e2fcdf5a3171fb669
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          env:
#            - name: SPRING_DATASOURCE_URL
#              value: "jdbc:mysql://mysql-service:3306/app?serverTimezone=Asia/Seoul"
#            - name: SPRING_DATASOURCE_USERNAME
#              value: "app"
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: "app12345"