apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-service-monitor
  namespace: eks-app
  labels:
    app.kubernetes.io/name: test-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-app
  namespaceSelector:
    any: true
  endpoints:
    - port: app-port
      path: /metrics
      interval: 20s