apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080" # Prometheus가 수집할 포트
spec:
  selector:
    app.kubernetes.io/name: test-app
  type: ClusterIP
  ports:
    - name: app-port
      protocol: TCP
      port: 8080 # 클러스터 내부에서 사용할 서비스 포트
      targetPort: 8080 # 서비스 전달 요청을 pod로 전달 포트